# ============================================================
# Prometheus Configuration
# ============================================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts/alert-rules.yml

scrape_configs:

  # ----------------------------------------------------------
  # Prometheus
  # ----------------------------------------------------------
  - job_name: "prometheus"

    static_configs:
      - targets:
          - "localhost:9090"

  # ----------------------------------------------------------
  # Backend Application
  # ----------------------------------------------------------
  - job_name: "request-system-backend"

    metrics_path: /metrics

    static_configs:
      - targets:
          - "host.docker.internal:30050"